#!/usr/bin/env python3

import speedtest

def callback(test_type: str):
    print(f'{test_type} test completed')


def bits_to_mbps(bits: int):
    return round(bits / 1e+6, 2)


# If you want to test against a specific server
# servers = [1234]
servers = []

# If you want to use a single threaded test
# threads = 1
threads = None

tester = speedtest.Speedtest()
print('Testing Net...')

try:
    tester.get_servers(servers)
    tester.get_best_server()
    while True:
        tester.download(threads=threads)
        tester.upload(threads=threads)
        results: speedtest.SpeedtestResults = tester.results
        print(f'{bits_to_mbps(results.download)} up | {bits_to_mbps(results.upload)} dn | {results.ping} p')
except KeyboardInterrupt:
    pass